[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Robert Usher <266585+dcchut@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rprompt = "1.0"
anyhow = "1.0"
rayon = "1.5"
crossbeam = "0.8"
num = "0.3"
ordered-float = "2.0"
pathfinding = "2.0"